#!/bin/bash

clear
echo "[1/5] Building..."
docker stop $(docker ps -aq -f ancestor=c9open)

clear
echo "[2/5] Building..."
docker rm $(docker ps -aq -f ancestor=c9open)

clear
echo "[3/5] Building..."
if [ $1 == -f &> /dev/null ]; then
    docker rmi $(docker images -aq)
else
    docker rmi c9open
fi

clear
echo "[4/5] Building..."

docker build -t c9open .

clear
echo "[5/5] Building..."

./start
