#!/bin/bash

#┌─────────────────────────────────────────────┐
#│ Для Cloud9 подходит только версия "v8.14.0" │
#└─────────────────────────────────────────────┘

if [[ $(node -v 2> /dev/null) != "v8.14.0" ]]; then
    apk add nodejs=8.14.0-r0 npm -X http://dl-cdn.alpinelinux.org/alpine/v3.8/main/
    clear
fi

#┌───────────────┐
#│ Запуск Cloud9 │
#└───────────────┘

node /root/.c9/server.js -l 0.0.0.0 -p 3000 -w / -a :
