#!/bin/bash

docker run -it -d --restart unless-stopped -p $1:8000 -p $2:3000 -e "SETTINGS=$(cat ./user.settings)" -e "WORKSPACE=$3" -v "$HOME/.ssh":/root/.sshsource -v "$HOME/cloud9/$3":/$3 -h $3 --name $3 c9open:latest

echo "localhost:$1"

